name: XAU 15m Cron

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render cron endpoint
        run: |
          curl -sS "https://xau-liquidity-bot.onrender.com/cron/run?token=${{ secrets.CRON_SECRET }}"
